---
apiVersion: v1
kind: Pod
metadata:
  name: tomcat-pod
  labels:
    author: ravicharan
    type: appserver
spec:
  containers:
    - name: mytomcat
      image: tomee
      ports: 
        - containerPort: 8080
          hostPort: 8080
...
