---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: ghost-rs
  namespace: test-ns
  labels:
    type: cms
    author: ravicharan
spec:
  replicas: 2
  selector:
    matchLabels:
      type: cms
  template:
    metadata:
      name: ghost-pod
      labels:
        type: cms
    spec:
      containers:
        - name: myghost
          image: ghost
          ports:
            - containerPort: 2368
              hostPort: 8080
          env:
            - name: NODE_ENV
              value: development


...
