---
apiVersion: v1
kind: Service
metadata:
  name: db-service
  labels:
    author: ravicharan
spec:
  type: ClusterIP
  ports:
    - targetPort: 5432
      port: 5432
  selector:
    app: db
    author: ravicharan


...
